# (target database)
url=jdbc:postgresql://localhost:5432/InnoUserDB
username=postgres
password=070696
driver=org.postgresql.Driver

# (reference database)
referenceUrl=hibernate:spring:com.innowise.user.entity? \
  dialect=org.hibernate.dialect.PostgreSQLDialect& \
  resolver=org.springframework.boot.orm.jpa.hibernate.SpringBootJpaHibernatePersistenceProviderResolver

outputChangeLogFile=src/main/resources/db/changelog/outputChangeLogFile.yaml
diffChangeLogFile=src/main/resources/db/changelog/diffChangeLogFile.yaml
changeLogFile=db/changelog/db.changelog-master.yaml

# Liquibase Hub (?????????)
#liquibase.hub.mode=off