server:
  port: 8082
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://order-postgres:5432/InnoOrderDB
    username: postgres
    password: 070696
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  web:
    resources:
      add-mappings: true

app:
  jwt:
    secret: ${JWT_SECRET}
    access-expiration: ${JWT_ACCESS_EXPIRATION:900000}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}

user:
  service:
    url: http://localhost:8081